<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="SmokeTestScenarios" duration-ms="170" started-at="2017-05-19T17:46:51Z" finished-at="2017-05-19T17:46:51Z">
    <groups>
    </groups>
    <test name="Sprint1" duration-ms="170" started-at="2017-05-19T17:46:51Z" finished-at="2017-05-19T17:46:51Z">
      <class name="testng.class3">
        <test-method status="FAIL" signature="testsnapchat()[pri:0, instance:testng.class3@d8355a8]" name="testsnapchat" duration-ms="10" started-at="2017-05-19T13:46:51Z" finished-at="2017-05-19T13:46:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testng.class3.testsnapchat(class3.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testsnapchat -->
      </class> <!-- testng.class3 -->
      <class name="testng.class2">
        <test-method status="PASS" signature="testfb()[pri:0, instance:testng.class2@46d56d67]" name="testfb" duration-ms="9" started-at="2017-05-19T13:46:51Z" finished-at="2017-05-19T13:46:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfb -->
      </class> <!-- testng.class2 -->
      <class name="testng.class1">
        <test-method status="PASS" signature="testtwitter()[pri:0, instance:testng.class1@4c70fda8]" name="testtwitter" duration-ms="30" started-at="2017-05-19T13:46:51Z" finished-at="2017-05-19T13:46:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwitter -->
      </class> <!-- testng.class1 -->
    </test> <!-- Sprint1 -->
  </suite> <!-- SmokeTestScenarios -->
</testng-results>
